name: 'salesforce_marketing_cloud_integration_tests'
version: '0.2.0'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  salesforce_marketing_cloud:
    salesforce_marketing_cloud_schema: sfmc_integration_tests_06
    salesforce_marketing_cloud_email_identifier: "email_data"
    salesforce_marketing_cloud_event_identifier: "event_data"
    salesforce_marketing_cloud_link_identifier: "link_data"
    salesforce_marketing_cloud_list_identifier: "list_data"
    salesforce_marketing_cloud_send_identifier: "send_data"
    salesforce_marketing_cloud_subscriber_identifier: "subscriber_data"
    salesforce_marketing_cloud_list_subscriber_identifier: "list_subscriber_data"
    salesforce_marketing_cloud_link_send_identifier: "link_send_data"
    salesforce_marketing_cloud_triggered_send_identifier: "triggered_send_data"

models: 
  +schema: "{{ 'sfmc_sqlw_tests' if target.name == 'databricks-sql' else 'salesforce_marketing_cloud' }}"
  # +schema: "salesforce_marketing_cloud_{{ var('directed_schema','dev') }}" ## To be used for validation testing

seeds:
  salesforce_marketing_cloud_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types: 
      id: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
      _fivetran_synced: "timestamp"
      _fivetran_start: "timestamp"
      _fivetran_end: "timestamp"
    event_data:
      +column_types: 
        created_date: "timestamp"
    subscriber_data:
      +column_types: 
        created_date: "timestamp"
        unsubscribed_date: "timestamp"